name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: yarn install
        
      - name: Build
        run: yarn build
        
      - name: Copy to docs
        run: |
          rm -rf docs
          cp -r dist docs
          
      - name: Deploy to main branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Deploy to docs folder"
          branch: main
          file_pattern: docs/